name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      ruby-version: 2.7.2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.ruby-version }}
        bundler: '2.2.33'
        bundler-cache: true

    - run: bundle exec middleman build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        keep_files: true
