name: Dev Deploy

on:
  push:
    branches: [ 'dev' ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      ruby-version: 2.7.2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.ruby-version }}
        bundler: '2.2.33'
        bundler-cache: true

    - run: bundle exec middleman build

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_KEY }}
        repository: slatedocs/slate
        tag_with_ref: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.0-8
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: dev
        publish_dir: ./build
        keep_files: true
